FROM ghcr.io/statgarten/statgarten:v20221027

RUN R -e "install.packages(c('reactable', 'ggpie', 'showtext'))"
RUN R -e "remotes::install_github('statgarten/colorpen')"
RUN R -e "remotes::install_github('statgarten/soroban')"
RUN R -e "remotes::install_github('statgarten/scissor')"
RUN R -e "remotes::install_github('statgarten/door')"

EXPOSE 3838
CMD ["/usr/bin/shiny-server"]
